/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.lftairline.kafka.avro;
@org.apache.avro.specific.AvroGenerated
public enum ArrivalStatus implements org.apache.avro.generic.GenericEnumSymbol<ArrivalStatus> {
  SCHEDULED, EN_ROUTE, APPROACHING, LANDED, ARRIVED, TAXIING, AT_GATE, DELAYED, DIVERTED, CANCELLED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"ArrivalStatus\",\"namespace\":\"com.lftairline.kafka.avro\",\"symbols\":[\"SCHEDULED\",\"EN_ROUTE\",\"APPROACHING\",\"LANDED\",\"ARRIVED\",\"TAXIING\",\"AT_GATE\",\"DELAYED\",\"DIVERTED\",\"CANCELLED\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
