/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.lftairline.kafka.avro;
@org.apache.avro.specific.AvroGenerated
public enum AssignmentType implements org.apache.avro.generic.GenericEnumSymbol<AssignmentType> {
  DEPARTURE, ARRIVAL, TURNAROUND  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"AssignmentType\",\"namespace\":\"com.lftairline.kafka.avro\",\"symbols\":[\"DEPARTURE\",\"ARRIVAL\",\"TURNAROUND\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
