/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.lftairline.kafka.avro;
@org.apache.avro.specific.AvroGenerated
public enum BaggageStatus implements org.apache.avro.generic.GenericEnumSymbol<BaggageStatus> {
  CHECKED_IN, IN_TRANSIT, LOADED, IN_FLIGHT, UNLOADED, CLAIMED, LOST  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"BaggageStatus\",\"namespace\":\"com.lftairline.kafka.avro\",\"symbols\":[\"CHECKED_IN\",\"IN_TRANSIT\",\"LOADED\",\"IN_FLIGHT\",\"UNLOADED\",\"CLAIMED\",\"LOST\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
