/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.lftairline.kafka.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** Represents a baggage tracking event for LFT Airline */
@org.apache.avro.specific.AvroGenerated
public class BaggageTracking extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 656069335614672624L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"BaggageTracking\",\"namespace\":\"com.lftairline.kafka.avro\",\"doc\":\"Represents a baggage tracking event for LFT Airline\",\"fields\":[{\"name\":\"bagId\",\"type\":\"string\",\"doc\":\"Unique baggage identifier\"},{\"name\":\"flightId\",\"type\":\"string\",\"doc\":\"Associated flight identifier\"},{\"name\":\"passengerId\",\"type\":\"string\",\"doc\":\"Passenger identifier who owns this bag\"},{\"name\":\"status\",\"type\":{\"type\":\"enum\",\"name\":\"BaggageStatus\",\"symbols\":[\"CHECKED_IN\",\"IN_TRANSIT\",\"LOADED\",\"IN_FLIGHT\",\"UNLOADED\",\"CLAIMED\",\"LOST\"]},\"doc\":\"Current baggage status\"},{\"name\":\"location\",\"type\":\"string\",\"doc\":\"Current location (airport code or facility)\"},{\"name\":\"weightKg\",\"type\":\"double\",\"doc\":\"Weight of baggage in kilograms\"},{\"name\":\"lastScanTime\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"},\"doc\":\"Last scan timestamp in epoch milliseconds\"},{\"name\":\"eventTimestamp\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"},\"doc\":\"When this event was generated\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();
  static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.TimestampMillisConversion());
  }

  private static final BinaryMessageEncoder<BaggageTracking> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<BaggageTracking> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<BaggageTracking> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<BaggageTracking> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<BaggageTracking> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this BaggageTracking to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a BaggageTracking from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a BaggageTracking instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static BaggageTracking fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Unique baggage identifier */
  private java.lang.CharSequence bagId;
  /** Associated flight identifier */
  private java.lang.CharSequence flightId;
  /** Passenger identifier who owns this bag */
  private java.lang.CharSequence passengerId;
  /** Current baggage status */
  private com.lftairline.kafka.avro.BaggageStatus status;
  /** Current location (airport code or facility) */
  private java.lang.CharSequence location;
  /** Weight of baggage in kilograms */
  private double weightKg;
  /** Last scan timestamp in epoch milliseconds */
  private java.time.Instant lastScanTime;
  /** When this event was generated */
  private java.time.Instant eventTimestamp;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public BaggageTracking() {}

  /**
   * All-args constructor.
   * @param bagId Unique baggage identifier
   * @param flightId Associated flight identifier
   * @param passengerId Passenger identifier who owns this bag
   * @param status Current baggage status
   * @param location Current location (airport code or facility)
   * @param weightKg Weight of baggage in kilograms
   * @param lastScanTime Last scan timestamp in epoch milliseconds
   * @param eventTimestamp When this event was generated
   */
  public BaggageTracking(java.lang.CharSequence bagId, java.lang.CharSequence flightId, java.lang.CharSequence passengerId, com.lftairline.kafka.avro.BaggageStatus status, java.lang.CharSequence location, java.lang.Double weightKg, java.time.Instant lastScanTime, java.time.Instant eventTimestamp) {
    this.bagId = bagId;
    this.flightId = flightId;
    this.passengerId = passengerId;
    this.status = status;
    this.location = location;
    this.weightKg = weightKg;
    this.lastScanTime = lastScanTime.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
    this.eventTimestamp = eventTimestamp.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return bagId;
    case 1: return flightId;
    case 2: return passengerId;
    case 3: return status;
    case 4: return location;
    case 5: return weightKg;
    case 6: return lastScanTime;
    case 7: return eventTimestamp;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      null,
      null,
      null,
      null,
      null,
      null,
      new org.apache.avro.data.TimeConversions.TimestampMillisConversion(),
      new org.apache.avro.data.TimeConversions.TimestampMillisConversion(),
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: bagId = (java.lang.CharSequence)value$; break;
    case 1: flightId = (java.lang.CharSequence)value$; break;
    case 2: passengerId = (java.lang.CharSequence)value$; break;
    case 3: status = (com.lftairline.kafka.avro.BaggageStatus)value$; break;
    case 4: location = (java.lang.CharSequence)value$; break;
    case 5: weightKg = (java.lang.Double)value$; break;
    case 6: lastScanTime = (java.time.Instant)value$; break;
    case 7: eventTimestamp = (java.time.Instant)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'bagId' field.
   * @return Unique baggage identifier
   */
  public java.lang.CharSequence getBagId() {
    return bagId;
  }


  /**
   * Sets the value of the 'bagId' field.
   * Unique baggage identifier
   * @param value the value to set.
   */
  public void setBagId(java.lang.CharSequence value) {
    this.bagId = value;
  }

  /**
   * Gets the value of the 'flightId' field.
   * @return Associated flight identifier
   */
  public java.lang.CharSequence getFlightId() {
    return flightId;
  }


  /**
   * Sets the value of the 'flightId' field.
   * Associated flight identifier
   * @param value the value to set.
   */
  public void setFlightId(java.lang.CharSequence value) {
    this.flightId = value;
  }

  /**
   * Gets the value of the 'passengerId' field.
   * @return Passenger identifier who owns this bag
   */
  public java.lang.CharSequence getPassengerId() {
    return passengerId;
  }


  /**
   * Sets the value of the 'passengerId' field.
   * Passenger identifier who owns this bag
   * @param value the value to set.
   */
  public void setPassengerId(java.lang.CharSequence value) {
    this.passengerId = value;
  }

  /**
   * Gets the value of the 'status' field.
   * @return Current baggage status
   */
  public com.lftairline.kafka.avro.BaggageStatus getStatus() {
    return status;
  }


  /**
   * Sets the value of the 'status' field.
   * Current baggage status
   * @param value the value to set.
   */
  public void setStatus(com.lftairline.kafka.avro.BaggageStatus value) {
    this.status = value;
  }

  /**
   * Gets the value of the 'location' field.
   * @return Current location (airport code or facility)
   */
  public java.lang.CharSequence getLocation() {
    return location;
  }


  /**
   * Sets the value of the 'location' field.
   * Current location (airport code or facility)
   * @param value the value to set.
   */
  public void setLocation(java.lang.CharSequence value) {
    this.location = value;
  }

  /**
   * Gets the value of the 'weightKg' field.
   * @return Weight of baggage in kilograms
   */
  public double getWeightKg() {
    return weightKg;
  }


  /**
   * Sets the value of the 'weightKg' field.
   * Weight of baggage in kilograms
   * @param value the value to set.
   */
  public void setWeightKg(double value) {
    this.weightKg = value;
  }

  /**
   * Gets the value of the 'lastScanTime' field.
   * @return Last scan timestamp in epoch milliseconds
   */
  public java.time.Instant getLastScanTime() {
    return lastScanTime;
  }


  /**
   * Sets the value of the 'lastScanTime' field.
   * Last scan timestamp in epoch milliseconds
   * @param value the value to set.
   */
  public void setLastScanTime(java.time.Instant value) {
    this.lastScanTime = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  /**
   * Gets the value of the 'eventTimestamp' field.
   * @return When this event was generated
   */
  public java.time.Instant getEventTimestamp() {
    return eventTimestamp;
  }


  /**
   * Sets the value of the 'eventTimestamp' field.
   * When this event was generated
   * @param value the value to set.
   */
  public void setEventTimestamp(java.time.Instant value) {
    this.eventTimestamp = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  /**
   * Creates a new BaggageTracking RecordBuilder.
   * @return A new BaggageTracking RecordBuilder
   */
  public static com.lftairline.kafka.avro.BaggageTracking.Builder newBuilder() {
    return new com.lftairline.kafka.avro.BaggageTracking.Builder();
  }

  /**
   * Creates a new BaggageTracking RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new BaggageTracking RecordBuilder
   */
  public static com.lftairline.kafka.avro.BaggageTracking.Builder newBuilder(com.lftairline.kafka.avro.BaggageTracking.Builder other) {
    if (other == null) {
      return new com.lftairline.kafka.avro.BaggageTracking.Builder();
    } else {
      return new com.lftairline.kafka.avro.BaggageTracking.Builder(other);
    }
  }

  /**
   * Creates a new BaggageTracking RecordBuilder by copying an existing BaggageTracking instance.
   * @param other The existing instance to copy.
   * @return A new BaggageTracking RecordBuilder
   */
  public static com.lftairline.kafka.avro.BaggageTracking.Builder newBuilder(com.lftairline.kafka.avro.BaggageTracking other) {
    if (other == null) {
      return new com.lftairline.kafka.avro.BaggageTracking.Builder();
    } else {
      return new com.lftairline.kafka.avro.BaggageTracking.Builder(other);
    }
  }

  /**
   * RecordBuilder for BaggageTracking instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<BaggageTracking>
    implements org.apache.avro.data.RecordBuilder<BaggageTracking> {

    /** Unique baggage identifier */
    private java.lang.CharSequence bagId;
    /** Associated flight identifier */
    private java.lang.CharSequence flightId;
    /** Passenger identifier who owns this bag */
    private java.lang.CharSequence passengerId;
    /** Current baggage status */
    private com.lftairline.kafka.avro.BaggageStatus status;
    /** Current location (airport code or facility) */
    private java.lang.CharSequence location;
    /** Weight of baggage in kilograms */
    private double weightKg;
    /** Last scan timestamp in epoch milliseconds */
    private java.time.Instant lastScanTime;
    /** When this event was generated */
    private java.time.Instant eventTimestamp;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.lftairline.kafka.avro.BaggageTracking.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.bagId)) {
        this.bagId = data().deepCopy(fields()[0].schema(), other.bagId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.flightId)) {
        this.flightId = data().deepCopy(fields()[1].schema(), other.flightId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.passengerId)) {
        this.passengerId = data().deepCopy(fields()[2].schema(), other.passengerId);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.status)) {
        this.status = data().deepCopy(fields()[3].schema(), other.status);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.location)) {
        this.location = data().deepCopy(fields()[4].schema(), other.location);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.weightKg)) {
        this.weightKg = data().deepCopy(fields()[5].schema(), other.weightKg);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.lastScanTime)) {
        this.lastScanTime = data().deepCopy(fields()[6].schema(), other.lastScanTime);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.eventTimestamp)) {
        this.eventTimestamp = data().deepCopy(fields()[7].schema(), other.eventTimestamp);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
    }

    /**
     * Creates a Builder by copying an existing BaggageTracking instance
     * @param other The existing instance to copy.
     */
    private Builder(com.lftairline.kafka.avro.BaggageTracking other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.bagId)) {
        this.bagId = data().deepCopy(fields()[0].schema(), other.bagId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.flightId)) {
        this.flightId = data().deepCopy(fields()[1].schema(), other.flightId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.passengerId)) {
        this.passengerId = data().deepCopy(fields()[2].schema(), other.passengerId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.status)) {
        this.status = data().deepCopy(fields()[3].schema(), other.status);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.location)) {
        this.location = data().deepCopy(fields()[4].schema(), other.location);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.weightKg)) {
        this.weightKg = data().deepCopy(fields()[5].schema(), other.weightKg);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.lastScanTime)) {
        this.lastScanTime = data().deepCopy(fields()[6].schema(), other.lastScanTime);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.eventTimestamp)) {
        this.eventTimestamp = data().deepCopy(fields()[7].schema(), other.eventTimestamp);
        fieldSetFlags()[7] = true;
      }
    }

    /**
      * Gets the value of the 'bagId' field.
      * Unique baggage identifier
      * @return The value.
      */
    public java.lang.CharSequence getBagId() {
      return bagId;
    }


    /**
      * Sets the value of the 'bagId' field.
      * Unique baggage identifier
      * @param value The value of 'bagId'.
      * @return This builder.
      */
    public com.lftairline.kafka.avro.BaggageTracking.Builder setBagId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.bagId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'bagId' field has been set.
      * Unique baggage identifier
      * @return True if the 'bagId' field has been set, false otherwise.
      */
    public boolean hasBagId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'bagId' field.
      * Unique baggage identifier
      * @return This builder.
      */
    public com.lftairline.kafka.avro.BaggageTracking.Builder clearBagId() {
      bagId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'flightId' field.
      * Associated flight identifier
      * @return The value.
      */
    public java.lang.CharSequence getFlightId() {
      return flightId;
    }


    /**
      * Sets the value of the 'flightId' field.
      * Associated flight identifier
      * @param value The value of 'flightId'.
      * @return This builder.
      */
    public com.lftairline.kafka.avro.BaggageTracking.Builder setFlightId(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.flightId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'flightId' field has been set.
      * Associated flight identifier
      * @return True if the 'flightId' field has been set, false otherwise.
      */
    public boolean hasFlightId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'flightId' field.
      * Associated flight identifier
      * @return This builder.
      */
    public com.lftairline.kafka.avro.BaggageTracking.Builder clearFlightId() {
      flightId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'passengerId' field.
      * Passenger identifier who owns this bag
      * @return The value.
      */
    public java.lang.CharSequence getPassengerId() {
      return passengerId;
    }


    /**
      * Sets the value of the 'passengerId' field.
      * Passenger identifier who owns this bag
      * @param value The value of 'passengerId'.
      * @return This builder.
      */
    public com.lftairline.kafka.avro.BaggageTracking.Builder setPassengerId(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.passengerId = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'passengerId' field has been set.
      * Passenger identifier who owns this bag
      * @return True if the 'passengerId' field has been set, false otherwise.
      */
    public boolean hasPassengerId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'passengerId' field.
      * Passenger identifier who owns this bag
      * @return This builder.
      */
    public com.lftairline.kafka.avro.BaggageTracking.Builder clearPassengerId() {
      passengerId = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'status' field.
      * Current baggage status
      * @return The value.
      */
    public com.lftairline.kafka.avro.BaggageStatus getStatus() {
      return status;
    }


    /**
      * Sets the value of the 'status' field.
      * Current baggage status
      * @param value The value of 'status'.
      * @return This builder.
      */
    public com.lftairline.kafka.avro.BaggageTracking.Builder setStatus(com.lftairline.kafka.avro.BaggageStatus value) {
      validate(fields()[3], value);
      this.status = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'status' field has been set.
      * Current baggage status
      * @return True if the 'status' field has been set, false otherwise.
      */
    public boolean hasStatus() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'status' field.
      * Current baggage status
      * @return This builder.
      */
    public com.lftairline.kafka.avro.BaggageTracking.Builder clearStatus() {
      status = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'location' field.
      * Current location (airport code or facility)
      * @return The value.
      */
    public java.lang.CharSequence getLocation() {
      return location;
    }


    /**
      * Sets the value of the 'location' field.
      * Current location (airport code or facility)
      * @param value The value of 'location'.
      * @return This builder.
      */
    public com.lftairline.kafka.avro.BaggageTracking.Builder setLocation(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.location = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'location' field has been set.
      * Current location (airport code or facility)
      * @return True if the 'location' field has been set, false otherwise.
      */
    public boolean hasLocation() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'location' field.
      * Current location (airport code or facility)
      * @return This builder.
      */
    public com.lftairline.kafka.avro.BaggageTracking.Builder clearLocation() {
      location = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'weightKg' field.
      * Weight of baggage in kilograms
      * @return The value.
      */
    public double getWeightKg() {
      return weightKg;
    }


    /**
      * Sets the value of the 'weightKg' field.
      * Weight of baggage in kilograms
      * @param value The value of 'weightKg'.
      * @return This builder.
      */
    public com.lftairline.kafka.avro.BaggageTracking.Builder setWeightKg(double value) {
      validate(fields()[5], value);
      this.weightKg = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'weightKg' field has been set.
      * Weight of baggage in kilograms
      * @return True if the 'weightKg' field has been set, false otherwise.
      */
    public boolean hasWeightKg() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'weightKg' field.
      * Weight of baggage in kilograms
      * @return This builder.
      */
    public com.lftairline.kafka.avro.BaggageTracking.Builder clearWeightKg() {
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'lastScanTime' field.
      * Last scan timestamp in epoch milliseconds
      * @return The value.
      */
    public java.time.Instant getLastScanTime() {
      return lastScanTime;
    }


    /**
      * Sets the value of the 'lastScanTime' field.
      * Last scan timestamp in epoch milliseconds
      * @param value The value of 'lastScanTime'.
      * @return This builder.
      */
    public com.lftairline.kafka.avro.BaggageTracking.Builder setLastScanTime(java.time.Instant value) {
      validate(fields()[6], value);
      this.lastScanTime = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'lastScanTime' field has been set.
      * Last scan timestamp in epoch milliseconds
      * @return True if the 'lastScanTime' field has been set, false otherwise.
      */
    public boolean hasLastScanTime() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'lastScanTime' field.
      * Last scan timestamp in epoch milliseconds
      * @return This builder.
      */
    public com.lftairline.kafka.avro.BaggageTracking.Builder clearLastScanTime() {
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'eventTimestamp' field.
      * When this event was generated
      * @return The value.
      */
    public java.time.Instant getEventTimestamp() {
      return eventTimestamp;
    }


    /**
      * Sets the value of the 'eventTimestamp' field.
      * When this event was generated
      * @param value The value of 'eventTimestamp'.
      * @return This builder.
      */
    public com.lftairline.kafka.avro.BaggageTracking.Builder setEventTimestamp(java.time.Instant value) {
      validate(fields()[7], value);
      this.eventTimestamp = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'eventTimestamp' field has been set.
      * When this event was generated
      * @return True if the 'eventTimestamp' field has been set, false otherwise.
      */
    public boolean hasEventTimestamp() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'eventTimestamp' field.
      * When this event was generated
      * @return This builder.
      */
    public com.lftairline.kafka.avro.BaggageTracking.Builder clearEventTimestamp() {
      fieldSetFlags()[7] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public BaggageTracking build() {
      try {
        BaggageTracking record = new BaggageTracking();
        record.bagId = fieldSetFlags()[0] ? this.bagId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.flightId = fieldSetFlags()[1] ? this.flightId : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.passengerId = fieldSetFlags()[2] ? this.passengerId : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.status = fieldSetFlags()[3] ? this.status : (com.lftairline.kafka.avro.BaggageStatus) defaultValue(fields()[3]);
        record.location = fieldSetFlags()[4] ? this.location : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.weightKg = fieldSetFlags()[5] ? this.weightKg : (java.lang.Double) defaultValue(fields()[5]);
        record.lastScanTime = fieldSetFlags()[6] ? this.lastScanTime : (java.time.Instant) defaultValue(fields()[6]);
        record.eventTimestamp = fieldSetFlags()[7] ? this.eventTimestamp : (java.time.Instant) defaultValue(fields()[7]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<BaggageTracking>
    WRITER$ = (org.apache.avro.io.DatumWriter<BaggageTracking>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<BaggageTracking>
    READER$ = (org.apache.avro.io.DatumReader<BaggageTracking>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










