/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.lftairline.kafka.avro;
@org.apache.avro.specific.AvroGenerated
public enum CheckinStatus implements org.apache.avro.generic.GenericEnumSymbol<CheckinStatus> {
  COMPLETED, PENDING_DOCS, PENDING_PAYMENT, CANCELLED, NO_SHOW  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"CheckinStatus\",\"namespace\":\"com.lftairline.kafka.avro\",\"symbols\":[\"COMPLETED\",\"PENDING_DOCS\",\"PENDING_PAYMENT\",\"CANCELLED\",\"NO_SHOW\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
