/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.lftairline.kafka.avro;
@org.apache.avro.specific.AvroGenerated
public enum CheckinType implements org.apache.avro.generic.GenericEnumSymbol<CheckinType> {
  ONLINE, MOBILE, KIOSK, COUNTER, CURBSIDE  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"CheckinType\",\"namespace\":\"com.lftairline.kafka.avro\",\"symbols\":[\"ONLINE\",\"MOBILE\",\"KIOSK\",\"COUNTER\",\"CURBSIDE\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
