/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.lftairline.kafka.avro;
@org.apache.avro.specific.AvroGenerated
public enum FlightStatus implements org.apache.avro.generic.GenericEnumSymbol<FlightStatus> {
  SCHEDULED, BOARDING, DEPARTED, IN_FLIGHT, ARRIVED, DELAYED, CANCELLED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"FlightStatus\",\"namespace\":\"com.lftairline.kafka.avro\",\"symbols\":[\"SCHEDULED\",\"BOARDING\",\"DEPARTED\",\"IN_FLIGHT\",\"ARRIVED\",\"DELAYED\",\"CANCELLED\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
