/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.lftairline.kafka.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** Represents a flight departure event for LFT Airline */
@org.apache.avro.specific.AvroGenerated
public class FlightDeparture extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 7896447383826442679L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"FlightDeparture\",\"namespace\":\"com.lftairline.kafka.avro\",\"doc\":\"Represents a flight departure event for LFT Airline\",\"fields\":[{\"name\":\"flightId\",\"type\":\"string\",\"doc\":\"Unique flight identifier (e.g., LFT100)\"},{\"name\":\"aircraftId\",\"type\":\"string\",\"doc\":\"Aircraft registration number\"},{\"name\":\"departureAirport\",\"type\":\"string\",\"doc\":\"IATA code of departure airport (e.g., JFK)\"},{\"name\":\"arrivalAirport\",\"type\":\"string\",\"doc\":\"IATA code of arrival airport (e.g., LAX)\"},{\"name\":\"scheduledDeparture\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"},\"doc\":\"Scheduled departure time in epoch milliseconds\"},{\"name\":\"actualDeparture\",\"type\":[\"null\",{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}],\"doc\":\"Actual departure time in epoch milliseconds (nullable)\",\"default\":null},{\"name\":\"status\",\"type\":{\"type\":\"enum\",\"name\":\"FlightStatus\",\"symbols\":[\"SCHEDULED\",\"BOARDING\",\"DEPARTED\",\"IN_FLIGHT\",\"ARRIVED\",\"DELAYED\",\"CANCELLED\"]},\"doc\":\"Current flight status\"},{\"name\":\"gate\",\"type\":[\"null\",\"string\"],\"doc\":\"Departure gate (nullable)\",\"default\":null},{\"name\":\"passengersBooked\",\"type\":\"int\",\"doc\":\"Number of passengers booked on this flight\"},{\"name\":\"eventTimestamp\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"},\"doc\":\"When this event was generated\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();
  static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.TimestampMillisConversion());
  }

  private static final BinaryMessageEncoder<FlightDeparture> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<FlightDeparture> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<FlightDeparture> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<FlightDeparture> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<FlightDeparture> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this FlightDeparture to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a FlightDeparture from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a FlightDeparture instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static FlightDeparture fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Unique flight identifier (e.g., LFT100) */
  private java.lang.CharSequence flightId;
  /** Aircraft registration number */
  private java.lang.CharSequence aircraftId;
  /** IATA code of departure airport (e.g., JFK) */
  private java.lang.CharSequence departureAirport;
  /** IATA code of arrival airport (e.g., LAX) */
  private java.lang.CharSequence arrivalAirport;
  /** Scheduled departure time in epoch milliseconds */
  private java.time.Instant scheduledDeparture;
  /** Actual departure time in epoch milliseconds (nullable) */
  private java.time.Instant actualDeparture;
  /** Current flight status */
  private com.lftairline.kafka.avro.FlightStatus status;
  /** Departure gate (nullable) */
  private java.lang.CharSequence gate;
  /** Number of passengers booked on this flight */
  private int passengersBooked;
  /** When this event was generated */
  private java.time.Instant eventTimestamp;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public FlightDeparture() {}

  /**
   * All-args constructor.
   * @param flightId Unique flight identifier (e.g., LFT100)
   * @param aircraftId Aircraft registration number
   * @param departureAirport IATA code of departure airport (e.g., JFK)
   * @param arrivalAirport IATA code of arrival airport (e.g., LAX)
   * @param scheduledDeparture Scheduled departure time in epoch milliseconds
   * @param actualDeparture Actual departure time in epoch milliseconds (nullable)
   * @param status Current flight status
   * @param gate Departure gate (nullable)
   * @param passengersBooked Number of passengers booked on this flight
   * @param eventTimestamp When this event was generated
   */
  public FlightDeparture(java.lang.CharSequence flightId, java.lang.CharSequence aircraftId, java.lang.CharSequence departureAirport, java.lang.CharSequence arrivalAirport, java.time.Instant scheduledDeparture, java.time.Instant actualDeparture, com.lftairline.kafka.avro.FlightStatus status, java.lang.CharSequence gate, java.lang.Integer passengersBooked, java.time.Instant eventTimestamp) {
    this.flightId = flightId;
    this.aircraftId = aircraftId;
    this.departureAirport = departureAirport;
    this.arrivalAirport = arrivalAirport;
    this.scheduledDeparture = scheduledDeparture.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
    this.actualDeparture = actualDeparture;
    this.status = status;
    this.gate = gate;
    this.passengersBooked = passengersBooked;
    this.eventTimestamp = eventTimestamp.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return flightId;
    case 1: return aircraftId;
    case 2: return departureAirport;
    case 3: return arrivalAirport;
    case 4: return scheduledDeparture;
    case 5: return actualDeparture;
    case 6: return status;
    case 7: return gate;
    case 8: return passengersBooked;
    case 9: return eventTimestamp;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      null,
      null,
      null,
      null,
      new org.apache.avro.data.TimeConversions.TimestampMillisConversion(),
      null,
      null,
      null,
      null,
      new org.apache.avro.data.TimeConversions.TimestampMillisConversion(),
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: flightId = (java.lang.CharSequence)value$; break;
    case 1: aircraftId = (java.lang.CharSequence)value$; break;
    case 2: departureAirport = (java.lang.CharSequence)value$; break;
    case 3: arrivalAirport = (java.lang.CharSequence)value$; break;
    case 4: scheduledDeparture = (java.time.Instant)value$; break;
    case 5: actualDeparture = (java.time.Instant)value$; break;
    case 6: status = (com.lftairline.kafka.avro.FlightStatus)value$; break;
    case 7: gate = (java.lang.CharSequence)value$; break;
    case 8: passengersBooked = (java.lang.Integer)value$; break;
    case 9: eventTimestamp = (java.time.Instant)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'flightId' field.
   * @return Unique flight identifier (e.g., LFT100)
   */
  public java.lang.CharSequence getFlightId() {
    return flightId;
  }


  /**
   * Sets the value of the 'flightId' field.
   * Unique flight identifier (e.g., LFT100)
   * @param value the value to set.
   */
  public void setFlightId(java.lang.CharSequence value) {
    this.flightId = value;
  }

  /**
   * Gets the value of the 'aircraftId' field.
   * @return Aircraft registration number
   */
  public java.lang.CharSequence getAircraftId() {
    return aircraftId;
  }


  /**
   * Sets the value of the 'aircraftId' field.
   * Aircraft registration number
   * @param value the value to set.
   */
  public void setAircraftId(java.lang.CharSequence value) {
    this.aircraftId = value;
  }

  /**
   * Gets the value of the 'departureAirport' field.
   * @return IATA code of departure airport (e.g., JFK)
   */
  public java.lang.CharSequence getDepartureAirport() {
    return departureAirport;
  }


  /**
   * Sets the value of the 'departureAirport' field.
   * IATA code of departure airport (e.g., JFK)
   * @param value the value to set.
   */
  public void setDepartureAirport(java.lang.CharSequence value) {
    this.departureAirport = value;
  }

  /**
   * Gets the value of the 'arrivalAirport' field.
   * @return IATA code of arrival airport (e.g., LAX)
   */
  public java.lang.CharSequence getArrivalAirport() {
    return arrivalAirport;
  }


  /**
   * Sets the value of the 'arrivalAirport' field.
   * IATA code of arrival airport (e.g., LAX)
   * @param value the value to set.
   */
  public void setArrivalAirport(java.lang.CharSequence value) {
    this.arrivalAirport = value;
  }

  /**
   * Gets the value of the 'scheduledDeparture' field.
   * @return Scheduled departure time in epoch milliseconds
   */
  public java.time.Instant getScheduledDeparture() {
    return scheduledDeparture;
  }


  /**
   * Sets the value of the 'scheduledDeparture' field.
   * Scheduled departure time in epoch milliseconds
   * @param value the value to set.
   */
  public void setScheduledDeparture(java.time.Instant value) {
    this.scheduledDeparture = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  /**
   * Gets the value of the 'actualDeparture' field.
   * @return Actual departure time in epoch milliseconds (nullable)
   */
  public java.time.Instant getActualDeparture() {
    return actualDeparture;
  }


  /**
   * Sets the value of the 'actualDeparture' field.
   * Actual departure time in epoch milliseconds (nullable)
   * @param value the value to set.
   */
  public void setActualDeparture(java.time.Instant value) {
    this.actualDeparture = value;
  }

  /**
   * Gets the value of the 'status' field.
   * @return Current flight status
   */
  public com.lftairline.kafka.avro.FlightStatus getStatus() {
    return status;
  }


  /**
   * Sets the value of the 'status' field.
   * Current flight status
   * @param value the value to set.
   */
  public void setStatus(com.lftairline.kafka.avro.FlightStatus value) {
    this.status = value;
  }

  /**
   * Gets the value of the 'gate' field.
   * @return Departure gate (nullable)
   */
  public java.lang.CharSequence getGate() {
    return gate;
  }


  /**
   * Sets the value of the 'gate' field.
   * Departure gate (nullable)
   * @param value the value to set.
   */
  public void setGate(java.lang.CharSequence value) {
    this.gate = value;
  }

  /**
   * Gets the value of the 'passengersBooked' field.
   * @return Number of passengers booked on this flight
   */
  public int getPassengersBooked() {
    return passengersBooked;
  }


  /**
   * Sets the value of the 'passengersBooked' field.
   * Number of passengers booked on this flight
   * @param value the value to set.
   */
  public void setPassengersBooked(int value) {
    this.passengersBooked = value;
  }

  /**
   * Gets the value of the 'eventTimestamp' field.
   * @return When this event was generated
   */
  public java.time.Instant getEventTimestamp() {
    return eventTimestamp;
  }


  /**
   * Sets the value of the 'eventTimestamp' field.
   * When this event was generated
   * @param value the value to set.
   */
  public void setEventTimestamp(java.time.Instant value) {
    this.eventTimestamp = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  /**
   * Creates a new FlightDeparture RecordBuilder.
   * @return A new FlightDeparture RecordBuilder
   */
  public static com.lftairline.kafka.avro.FlightDeparture.Builder newBuilder() {
    return new com.lftairline.kafka.avro.FlightDeparture.Builder();
  }

  /**
   * Creates a new FlightDeparture RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new FlightDeparture RecordBuilder
   */
  public static com.lftairline.kafka.avro.FlightDeparture.Builder newBuilder(com.lftairline.kafka.avro.FlightDeparture.Builder other) {
    if (other == null) {
      return new com.lftairline.kafka.avro.FlightDeparture.Builder();
    } else {
      return new com.lftairline.kafka.avro.FlightDeparture.Builder(other);
    }
  }

  /**
   * Creates a new FlightDeparture RecordBuilder by copying an existing FlightDeparture instance.
   * @param other The existing instance to copy.
   * @return A new FlightDeparture RecordBuilder
   */
  public static com.lftairline.kafka.avro.FlightDeparture.Builder newBuilder(com.lftairline.kafka.avro.FlightDeparture other) {
    if (other == null) {
      return new com.lftairline.kafka.avro.FlightDeparture.Builder();
    } else {
      return new com.lftairline.kafka.avro.FlightDeparture.Builder(other);
    }
  }

  /**
   * RecordBuilder for FlightDeparture instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<FlightDeparture>
    implements org.apache.avro.data.RecordBuilder<FlightDeparture> {

    /** Unique flight identifier (e.g., LFT100) */
    private java.lang.CharSequence flightId;
    /** Aircraft registration number */
    private java.lang.CharSequence aircraftId;
    /** IATA code of departure airport (e.g., JFK) */
    private java.lang.CharSequence departureAirport;
    /** IATA code of arrival airport (e.g., LAX) */
    private java.lang.CharSequence arrivalAirport;
    /** Scheduled departure time in epoch milliseconds */
    private java.time.Instant scheduledDeparture;
    /** Actual departure time in epoch milliseconds (nullable) */
    private java.time.Instant actualDeparture;
    /** Current flight status */
    private com.lftairline.kafka.avro.FlightStatus status;
    /** Departure gate (nullable) */
    private java.lang.CharSequence gate;
    /** Number of passengers booked on this flight */
    private int passengersBooked;
    /** When this event was generated */
    private java.time.Instant eventTimestamp;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.lftairline.kafka.avro.FlightDeparture.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.flightId)) {
        this.flightId = data().deepCopy(fields()[0].schema(), other.flightId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.aircraftId)) {
        this.aircraftId = data().deepCopy(fields()[1].schema(), other.aircraftId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.departureAirport)) {
        this.departureAirport = data().deepCopy(fields()[2].schema(), other.departureAirport);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.arrivalAirport)) {
        this.arrivalAirport = data().deepCopy(fields()[3].schema(), other.arrivalAirport);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.scheduledDeparture)) {
        this.scheduledDeparture = data().deepCopy(fields()[4].schema(), other.scheduledDeparture);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.actualDeparture)) {
        this.actualDeparture = data().deepCopy(fields()[5].schema(), other.actualDeparture);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.status)) {
        this.status = data().deepCopy(fields()[6].schema(), other.status);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.gate)) {
        this.gate = data().deepCopy(fields()[7].schema(), other.gate);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (isValidValue(fields()[8], other.passengersBooked)) {
        this.passengersBooked = data().deepCopy(fields()[8].schema(), other.passengersBooked);
        fieldSetFlags()[8] = other.fieldSetFlags()[8];
      }
      if (isValidValue(fields()[9], other.eventTimestamp)) {
        this.eventTimestamp = data().deepCopy(fields()[9].schema(), other.eventTimestamp);
        fieldSetFlags()[9] = other.fieldSetFlags()[9];
      }
    }

    /**
     * Creates a Builder by copying an existing FlightDeparture instance
     * @param other The existing instance to copy.
     */
    private Builder(com.lftairline.kafka.avro.FlightDeparture other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.flightId)) {
        this.flightId = data().deepCopy(fields()[0].schema(), other.flightId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.aircraftId)) {
        this.aircraftId = data().deepCopy(fields()[1].schema(), other.aircraftId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.departureAirport)) {
        this.departureAirport = data().deepCopy(fields()[2].schema(), other.departureAirport);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.arrivalAirport)) {
        this.arrivalAirport = data().deepCopy(fields()[3].schema(), other.arrivalAirport);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.scheduledDeparture)) {
        this.scheduledDeparture = data().deepCopy(fields()[4].schema(), other.scheduledDeparture);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.actualDeparture)) {
        this.actualDeparture = data().deepCopy(fields()[5].schema(), other.actualDeparture);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.status)) {
        this.status = data().deepCopy(fields()[6].schema(), other.status);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.gate)) {
        this.gate = data().deepCopy(fields()[7].schema(), other.gate);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.passengersBooked)) {
        this.passengersBooked = data().deepCopy(fields()[8].schema(), other.passengersBooked);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.eventTimestamp)) {
        this.eventTimestamp = data().deepCopy(fields()[9].schema(), other.eventTimestamp);
        fieldSetFlags()[9] = true;
      }
    }

    /**
      * Gets the value of the 'flightId' field.
      * Unique flight identifier (e.g., LFT100)
      * @return The value.
      */
    public java.lang.CharSequence getFlightId() {
      return flightId;
    }


    /**
      * Sets the value of the 'flightId' field.
      * Unique flight identifier (e.g., LFT100)
      * @param value The value of 'flightId'.
      * @return This builder.
      */
    public com.lftairline.kafka.avro.FlightDeparture.Builder setFlightId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.flightId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'flightId' field has been set.
      * Unique flight identifier (e.g., LFT100)
      * @return True if the 'flightId' field has been set, false otherwise.
      */
    public boolean hasFlightId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'flightId' field.
      * Unique flight identifier (e.g., LFT100)
      * @return This builder.
      */
    public com.lftairline.kafka.avro.FlightDeparture.Builder clearFlightId() {
      flightId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'aircraftId' field.
      * Aircraft registration number
      * @return The value.
      */
    public java.lang.CharSequence getAircraftId() {
      return aircraftId;
    }


    /**
      * Sets the value of the 'aircraftId' field.
      * Aircraft registration number
      * @param value The value of 'aircraftId'.
      * @return This builder.
      */
    public com.lftairline.kafka.avro.FlightDeparture.Builder setAircraftId(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.aircraftId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'aircraftId' field has been set.
      * Aircraft registration number
      * @return True if the 'aircraftId' field has been set, false otherwise.
      */
    public boolean hasAircraftId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'aircraftId' field.
      * Aircraft registration number
      * @return This builder.
      */
    public com.lftairline.kafka.avro.FlightDeparture.Builder clearAircraftId() {
      aircraftId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'departureAirport' field.
      * IATA code of departure airport (e.g., JFK)
      * @return The value.
      */
    public java.lang.CharSequence getDepartureAirport() {
      return departureAirport;
    }


    /**
      * Sets the value of the 'departureAirport' field.
      * IATA code of departure airport (e.g., JFK)
      * @param value The value of 'departureAirport'.
      * @return This builder.
      */
    public com.lftairline.kafka.avro.FlightDeparture.Builder setDepartureAirport(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.departureAirport = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'departureAirport' field has been set.
      * IATA code of departure airport (e.g., JFK)
      * @return True if the 'departureAirport' field has been set, false otherwise.
      */
    public boolean hasDepartureAirport() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'departureAirport' field.
      * IATA code of departure airport (e.g., JFK)
      * @return This builder.
      */
    public com.lftairline.kafka.avro.FlightDeparture.Builder clearDepartureAirport() {
      departureAirport = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'arrivalAirport' field.
      * IATA code of arrival airport (e.g., LAX)
      * @return The value.
      */
    public java.lang.CharSequence getArrivalAirport() {
      return arrivalAirport;
    }


    /**
      * Sets the value of the 'arrivalAirport' field.
      * IATA code of arrival airport (e.g., LAX)
      * @param value The value of 'arrivalAirport'.
      * @return This builder.
      */
    public com.lftairline.kafka.avro.FlightDeparture.Builder setArrivalAirport(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.arrivalAirport = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'arrivalAirport' field has been set.
      * IATA code of arrival airport (e.g., LAX)
      * @return True if the 'arrivalAirport' field has been set, false otherwise.
      */
    public boolean hasArrivalAirport() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'arrivalAirport' field.
      * IATA code of arrival airport (e.g., LAX)
      * @return This builder.
      */
    public com.lftairline.kafka.avro.FlightDeparture.Builder clearArrivalAirport() {
      arrivalAirport = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'scheduledDeparture' field.
      * Scheduled departure time in epoch milliseconds
      * @return The value.
      */
    public java.time.Instant getScheduledDeparture() {
      return scheduledDeparture;
    }


    /**
      * Sets the value of the 'scheduledDeparture' field.
      * Scheduled departure time in epoch milliseconds
      * @param value The value of 'scheduledDeparture'.
      * @return This builder.
      */
    public com.lftairline.kafka.avro.FlightDeparture.Builder setScheduledDeparture(java.time.Instant value) {
      validate(fields()[4], value);
      this.scheduledDeparture = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'scheduledDeparture' field has been set.
      * Scheduled departure time in epoch milliseconds
      * @return True if the 'scheduledDeparture' field has been set, false otherwise.
      */
    public boolean hasScheduledDeparture() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'scheduledDeparture' field.
      * Scheduled departure time in epoch milliseconds
      * @return This builder.
      */
    public com.lftairline.kafka.avro.FlightDeparture.Builder clearScheduledDeparture() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'actualDeparture' field.
      * Actual departure time in epoch milliseconds (nullable)
      * @return The value.
      */
    public java.time.Instant getActualDeparture() {
      return actualDeparture;
    }


    /**
      * Sets the value of the 'actualDeparture' field.
      * Actual departure time in epoch milliseconds (nullable)
      * @param value The value of 'actualDeparture'.
      * @return This builder.
      */
    public com.lftairline.kafka.avro.FlightDeparture.Builder setActualDeparture(java.time.Instant value) {
      validate(fields()[5], value);
      this.actualDeparture = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'actualDeparture' field has been set.
      * Actual departure time in epoch milliseconds (nullable)
      * @return True if the 'actualDeparture' field has been set, false otherwise.
      */
    public boolean hasActualDeparture() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'actualDeparture' field.
      * Actual departure time in epoch milliseconds (nullable)
      * @return This builder.
      */
    public com.lftairline.kafka.avro.FlightDeparture.Builder clearActualDeparture() {
      actualDeparture = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'status' field.
      * Current flight status
      * @return The value.
      */
    public com.lftairline.kafka.avro.FlightStatus getStatus() {
      return status;
    }


    /**
      * Sets the value of the 'status' field.
      * Current flight status
      * @param value The value of 'status'.
      * @return This builder.
      */
    public com.lftairline.kafka.avro.FlightDeparture.Builder setStatus(com.lftairline.kafka.avro.FlightStatus value) {
      validate(fields()[6], value);
      this.status = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'status' field has been set.
      * Current flight status
      * @return True if the 'status' field has been set, false otherwise.
      */
    public boolean hasStatus() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'status' field.
      * Current flight status
      * @return This builder.
      */
    public com.lftairline.kafka.avro.FlightDeparture.Builder clearStatus() {
      status = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'gate' field.
      * Departure gate (nullable)
      * @return The value.
      */
    public java.lang.CharSequence getGate() {
      return gate;
    }


    /**
      * Sets the value of the 'gate' field.
      * Departure gate (nullable)
      * @param value The value of 'gate'.
      * @return This builder.
      */
    public com.lftairline.kafka.avro.FlightDeparture.Builder setGate(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this.gate = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'gate' field has been set.
      * Departure gate (nullable)
      * @return True if the 'gate' field has been set, false otherwise.
      */
    public boolean hasGate() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'gate' field.
      * Departure gate (nullable)
      * @return This builder.
      */
    public com.lftairline.kafka.avro.FlightDeparture.Builder clearGate() {
      gate = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'passengersBooked' field.
      * Number of passengers booked on this flight
      * @return The value.
      */
    public int getPassengersBooked() {
      return passengersBooked;
    }


    /**
      * Sets the value of the 'passengersBooked' field.
      * Number of passengers booked on this flight
      * @param value The value of 'passengersBooked'.
      * @return This builder.
      */
    public com.lftairline.kafka.avro.FlightDeparture.Builder setPassengersBooked(int value) {
      validate(fields()[8], value);
      this.passengersBooked = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'passengersBooked' field has been set.
      * Number of passengers booked on this flight
      * @return True if the 'passengersBooked' field has been set, false otherwise.
      */
    public boolean hasPassengersBooked() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'passengersBooked' field.
      * Number of passengers booked on this flight
      * @return This builder.
      */
    public com.lftairline.kafka.avro.FlightDeparture.Builder clearPassengersBooked() {
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'eventTimestamp' field.
      * When this event was generated
      * @return The value.
      */
    public java.time.Instant getEventTimestamp() {
      return eventTimestamp;
    }


    /**
      * Sets the value of the 'eventTimestamp' field.
      * When this event was generated
      * @param value The value of 'eventTimestamp'.
      * @return This builder.
      */
    public com.lftairline.kafka.avro.FlightDeparture.Builder setEventTimestamp(java.time.Instant value) {
      validate(fields()[9], value);
      this.eventTimestamp = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'eventTimestamp' field has been set.
      * When this event was generated
      * @return True if the 'eventTimestamp' field has been set, false otherwise.
      */
    public boolean hasEventTimestamp() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'eventTimestamp' field.
      * When this event was generated
      * @return This builder.
      */
    public com.lftairline.kafka.avro.FlightDeparture.Builder clearEventTimestamp() {
      fieldSetFlags()[9] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public FlightDeparture build() {
      try {
        FlightDeparture record = new FlightDeparture();
        record.flightId = fieldSetFlags()[0] ? this.flightId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.aircraftId = fieldSetFlags()[1] ? this.aircraftId : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.departureAirport = fieldSetFlags()[2] ? this.departureAirport : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.arrivalAirport = fieldSetFlags()[3] ? this.arrivalAirport : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.scheduledDeparture = fieldSetFlags()[4] ? this.scheduledDeparture : (java.time.Instant) defaultValue(fields()[4]);
        record.actualDeparture = fieldSetFlags()[5] ? this.actualDeparture : (java.time.Instant) defaultValue(fields()[5]);
        record.status = fieldSetFlags()[6] ? this.status : (com.lftairline.kafka.avro.FlightStatus) defaultValue(fields()[6]);
        record.gate = fieldSetFlags()[7] ? this.gate : (java.lang.CharSequence) defaultValue(fields()[7]);
        record.passengersBooked = fieldSetFlags()[8] ? this.passengersBooked : (java.lang.Integer) defaultValue(fields()[8]);
        record.eventTimestamp = fieldSetFlags()[9] ? this.eventTimestamp : (java.time.Instant) defaultValue(fields()[9]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<FlightDeparture>
    WRITER$ = (org.apache.avro.io.DatumWriter<FlightDeparture>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<FlightDeparture>
    READER$ = (org.apache.avro.io.DatumReader<FlightDeparture>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










