/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.lftairline.kafka.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class GateEquipment extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -8728842393969118314L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"GateEquipment\",\"namespace\":\"com.lftairline.kafka.avro\",\"fields\":[{\"name\":\"jetBridge\",\"type\":\"boolean\",\"doc\":\"Whether gate has a jet bridge\",\"default\":false},{\"name\":\"groundPower\",\"type\":\"boolean\",\"doc\":\"Whether gate has ground power available\",\"default\":false},{\"name\":\"airConditioning\",\"type\":\"boolean\",\"doc\":\"Whether gate has pre-conditioned air\",\"default\":false}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<GateEquipment> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<GateEquipment> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<GateEquipment> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<GateEquipment> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<GateEquipment> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this GateEquipment to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a GateEquipment from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a GateEquipment instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static GateEquipment fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Whether gate has a jet bridge */
  private boolean jetBridge;
  /** Whether gate has ground power available */
  private boolean groundPower;
  /** Whether gate has pre-conditioned air */
  private boolean airConditioning;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public GateEquipment() {}

  /**
   * All-args constructor.
   * @param jetBridge Whether gate has a jet bridge
   * @param groundPower Whether gate has ground power available
   * @param airConditioning Whether gate has pre-conditioned air
   */
  public GateEquipment(java.lang.Boolean jetBridge, java.lang.Boolean groundPower, java.lang.Boolean airConditioning) {
    this.jetBridge = jetBridge;
    this.groundPower = groundPower;
    this.airConditioning = airConditioning;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return jetBridge;
    case 1: return groundPower;
    case 2: return airConditioning;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: jetBridge = (java.lang.Boolean)value$; break;
    case 1: groundPower = (java.lang.Boolean)value$; break;
    case 2: airConditioning = (java.lang.Boolean)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'jetBridge' field.
   * @return Whether gate has a jet bridge
   */
  public boolean getJetBridge() {
    return jetBridge;
  }


  /**
   * Sets the value of the 'jetBridge' field.
   * Whether gate has a jet bridge
   * @param value the value to set.
   */
  public void setJetBridge(boolean value) {
    this.jetBridge = value;
  }

  /**
   * Gets the value of the 'groundPower' field.
   * @return Whether gate has ground power available
   */
  public boolean getGroundPower() {
    return groundPower;
  }


  /**
   * Sets the value of the 'groundPower' field.
   * Whether gate has ground power available
   * @param value the value to set.
   */
  public void setGroundPower(boolean value) {
    this.groundPower = value;
  }

  /**
   * Gets the value of the 'airConditioning' field.
   * @return Whether gate has pre-conditioned air
   */
  public boolean getAirConditioning() {
    return airConditioning;
  }


  /**
   * Sets the value of the 'airConditioning' field.
   * Whether gate has pre-conditioned air
   * @param value the value to set.
   */
  public void setAirConditioning(boolean value) {
    this.airConditioning = value;
  }

  /**
   * Creates a new GateEquipment RecordBuilder.
   * @return A new GateEquipment RecordBuilder
   */
  public static com.lftairline.kafka.avro.GateEquipment.Builder newBuilder() {
    return new com.lftairline.kafka.avro.GateEquipment.Builder();
  }

  /**
   * Creates a new GateEquipment RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new GateEquipment RecordBuilder
   */
  public static com.lftairline.kafka.avro.GateEquipment.Builder newBuilder(com.lftairline.kafka.avro.GateEquipment.Builder other) {
    if (other == null) {
      return new com.lftairline.kafka.avro.GateEquipment.Builder();
    } else {
      return new com.lftairline.kafka.avro.GateEquipment.Builder(other);
    }
  }

  /**
   * Creates a new GateEquipment RecordBuilder by copying an existing GateEquipment instance.
   * @param other The existing instance to copy.
   * @return A new GateEquipment RecordBuilder
   */
  public static com.lftairline.kafka.avro.GateEquipment.Builder newBuilder(com.lftairline.kafka.avro.GateEquipment other) {
    if (other == null) {
      return new com.lftairline.kafka.avro.GateEquipment.Builder();
    } else {
      return new com.lftairline.kafka.avro.GateEquipment.Builder(other);
    }
  }

  /**
   * RecordBuilder for GateEquipment instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<GateEquipment>
    implements org.apache.avro.data.RecordBuilder<GateEquipment> {

    /** Whether gate has a jet bridge */
    private boolean jetBridge;
    /** Whether gate has ground power available */
    private boolean groundPower;
    /** Whether gate has pre-conditioned air */
    private boolean airConditioning;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.lftairline.kafka.avro.GateEquipment.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.jetBridge)) {
        this.jetBridge = data().deepCopy(fields()[0].schema(), other.jetBridge);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.groundPower)) {
        this.groundPower = data().deepCopy(fields()[1].schema(), other.groundPower);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.airConditioning)) {
        this.airConditioning = data().deepCopy(fields()[2].schema(), other.airConditioning);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing GateEquipment instance
     * @param other The existing instance to copy.
     */
    private Builder(com.lftairline.kafka.avro.GateEquipment other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.jetBridge)) {
        this.jetBridge = data().deepCopy(fields()[0].schema(), other.jetBridge);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.groundPower)) {
        this.groundPower = data().deepCopy(fields()[1].schema(), other.groundPower);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.airConditioning)) {
        this.airConditioning = data().deepCopy(fields()[2].schema(), other.airConditioning);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'jetBridge' field.
      * Whether gate has a jet bridge
      * @return The value.
      */
    public boolean getJetBridge() {
      return jetBridge;
    }


    /**
      * Sets the value of the 'jetBridge' field.
      * Whether gate has a jet bridge
      * @param value The value of 'jetBridge'.
      * @return This builder.
      */
    public com.lftairline.kafka.avro.GateEquipment.Builder setJetBridge(boolean value) {
      validate(fields()[0], value);
      this.jetBridge = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'jetBridge' field has been set.
      * Whether gate has a jet bridge
      * @return True if the 'jetBridge' field has been set, false otherwise.
      */
    public boolean hasJetBridge() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'jetBridge' field.
      * Whether gate has a jet bridge
      * @return This builder.
      */
    public com.lftairline.kafka.avro.GateEquipment.Builder clearJetBridge() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'groundPower' field.
      * Whether gate has ground power available
      * @return The value.
      */
    public boolean getGroundPower() {
      return groundPower;
    }


    /**
      * Sets the value of the 'groundPower' field.
      * Whether gate has ground power available
      * @param value The value of 'groundPower'.
      * @return This builder.
      */
    public com.lftairline.kafka.avro.GateEquipment.Builder setGroundPower(boolean value) {
      validate(fields()[1], value);
      this.groundPower = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'groundPower' field has been set.
      * Whether gate has ground power available
      * @return True if the 'groundPower' field has been set, false otherwise.
      */
    public boolean hasGroundPower() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'groundPower' field.
      * Whether gate has ground power available
      * @return This builder.
      */
    public com.lftairline.kafka.avro.GateEquipment.Builder clearGroundPower() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'airConditioning' field.
      * Whether gate has pre-conditioned air
      * @return The value.
      */
    public boolean getAirConditioning() {
      return airConditioning;
    }


    /**
      * Sets the value of the 'airConditioning' field.
      * Whether gate has pre-conditioned air
      * @param value The value of 'airConditioning'.
      * @return This builder.
      */
    public com.lftairline.kafka.avro.GateEquipment.Builder setAirConditioning(boolean value) {
      validate(fields()[2], value);
      this.airConditioning = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'airConditioning' field has been set.
      * Whether gate has pre-conditioned air
      * @return True if the 'airConditioning' field has been set, false otherwise.
      */
    public boolean hasAirConditioning() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'airConditioning' field.
      * Whether gate has pre-conditioned air
      * @return This builder.
      */
    public com.lftairline.kafka.avro.GateEquipment.Builder clearAirConditioning() {
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public GateEquipment build() {
      try {
        GateEquipment record = new GateEquipment();
        record.jetBridge = fieldSetFlags()[0] ? this.jetBridge : (java.lang.Boolean) defaultValue(fields()[0]);
        record.groundPower = fieldSetFlags()[1] ? this.groundPower : (java.lang.Boolean) defaultValue(fields()[1]);
        record.airConditioning = fieldSetFlags()[2] ? this.airConditioning : (java.lang.Boolean) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<GateEquipment>
    WRITER$ = (org.apache.avro.io.DatumWriter<GateEquipment>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<GateEquipment>
    READER$ = (org.apache.avro.io.DatumReader<GateEquipment>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeBoolean(this.jetBridge);

    out.writeBoolean(this.groundPower);

    out.writeBoolean(this.airConditioning);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.jetBridge = in.readBoolean();

      this.groundPower = in.readBoolean();

      this.airConditioning = in.readBoolean();

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.jetBridge = in.readBoolean();
          break;

        case 1:
          this.groundPower = in.readBoolean();
          break;

        case 2:
          this.airConditioning = in.readBoolean();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










