/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.lftairline.kafka.avro;
@org.apache.avro.specific.AvroGenerated
public enum GateStatus implements org.apache.avro.generic.GenericEnumSymbol<GateStatus> {
  ASSIGNED, CONFIRMED, CHANGED, OCCUPIED, AVAILABLE, MAINTENANCE, CLOSED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"GateStatus\",\"namespace\":\"com.lftairline.kafka.avro\",\"symbols\":[\"ASSIGNED\",\"CONFIRMED\",\"CHANGED\",\"OCCUPIED\",\"AVAILABLE\",\"MAINTENANCE\",\"CLOSED\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
