/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.lftairline.kafka.avro;
@org.apache.avro.specific.AvroGenerated
public enum TravelClass implements org.apache.avro.generic.GenericEnumSymbol<TravelClass> {
  ECONOMY, PREMIUM_ECONOMY, BUSINESS, FIRST  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"TravelClass\",\"namespace\":\"com.lftairline.kafka.avro\",\"symbols\":[\"ECONOMY\",\"PREMIUM_ECONOMY\",\"BUSINESS\",\"FIRST\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
